/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.poo;


import org.jfree.chart.*;

import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.*;
import org.jfree.data.xy.*;

import com.google.gson.Gson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author RAFAEL
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        Gson gson = new Gson();
        String fileContent = null;
        try {
            fileContent = new String(Files.readAllBytes(Paths.get("datafile.json")));
        } catch (IOException ex) {
            Logger.getLogger(TrabalhoPoo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JData dataCollection = gson.fromJson(fileContent, JData.class);
        dataCollection.getData().stream().forEach((record) -> {
            if(record.getYear() == 2000)
                jComboBoxCountry.addItem(record.getCountry());
        });
        
        this.setLocationRelativeTo(null);
        this.jPanelGraphic.setVisible(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jComboBoxCountry = new javax.swing.JComboBox<>();
        jSliderStartYear = new javax.swing.JSlider();
        jSliderEndYear = new javax.swing.JSlider();
        jButtonGenerate = new javax.swing.JButton();
        jLayeredPaneGraphic = new javax.swing.JLayeredPane();
        jPanelGraphic = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCountryActionPerformed(evt);
            }
        });

        jSliderStartYear.setMajorTickSpacing(1);
        jSliderStartYear.setMaximum(2015);
        jSliderStartYear.setMinimum(1990);
        jSliderStartYear.setMinorTickSpacing(1);
        jSliderStartYear.setSnapToTicks(true);
        jSliderStartYear.setToolTipText("");
        jSliderStartYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStartYearStateChanged(evt);
            }
        });

        jSliderEndYear.setMajorTickSpacing(1);
        jSliderEndYear.setMaximum(2015);
        jSliderEndYear.setMinimum(1990);
        jSliderEndYear.setMinorTickSpacing(1);
        jSliderEndYear.setSnapToTicks(true);
        jSliderEndYear.setValue(2015);
        jSliderEndYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderEndYearStateChanged(evt);
            }
        });

        jButtonGenerate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGenerate.setText("Gerar Gráfico");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jPanelGraphic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelGraphicLayout = new javax.swing.GroupLayout(jPanelGraphic);
        jPanelGraphic.setLayout(jPanelGraphicLayout);
        jPanelGraphicLayout.setHorizontalGroup(
            jPanelGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanelGraphicLayout.setVerticalGroup(
            jPanelGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jLayeredPaneGraphic.setLayer(jPanelGraphic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneGraphicLayout = new javax.swing.GroupLayout(jLayeredPaneGraphic);
        jLayeredPaneGraphic.setLayout(jLayeredPaneGraphicLayout);
        jLayeredPaneGraphicLayout.setHorizontalGroup(
            jLayeredPaneGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneGraphicLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelGraphic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPaneGraphicLayout.setVerticalGroup(
            jLayeredPaneGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGraphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Ano Inicial:");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Ano Final:");

        jLabel3.setText("1990");

        jLabel4.setText("2015");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setText("Energia Renovável por País");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("País:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSliderStartYear, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addComponent(jSliderEndYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButtonGenerate)))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPaneGraphic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPaneGraphic)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jButtonGenerate)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCountryActionPerformed

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        ChartPanel panel;
        JFreeChart chart = null;
        
        XYSplineRenderer renderer = new XYSplineRenderer();
        XYSeriesCollection dataset = new XYSeriesCollection();
        
        ValueAxis x = new NumberAxis();
        ValueAxis y = new NumberAxis();
        
        XYSeries serie = new XYSeries("% de Energia Renovável");
        
        XYPlot plot;
        jPanelGraphic.removeAll();
        
        Gson gson = new Gson();
        String fileContent = null;
        try {
            fileContent = new String(Files.readAllBytes(Paths.get("datafile.json")));
        } catch (IOException ex) {
            Logger.getLogger(TrabalhoPoo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JData dataCollection = gson.fromJson(fileContent, JData.class);
        dataCollection.getData().stream().forEach((record) -> {
            if(record.getCountry().equals(jComboBoxCountry.getSelectedItem()) == true && record.getYear() >= jSliderStartYear.getValue() && record.getYear() <= jSliderEndYear.getValue() && record.getValue() != 0)
            {
                serie.add(Float.parseFloat(String.valueOf(record.getYear())), Float.parseFloat(String.valueOf(record.getValue())));
            }
        });
        
        dataset.addSeries(serie);
        dataset.setAutoWidth(false);
        dataset.setIntervalPositionFactor(0.0);
        
        x.setAutoRange(false);
        x.setRangeAboutValue(2000.0, 35.0);
        x.setLabel("Ano");
        y.setLabel("Valor");
        plot = new XYPlot(dataset,x,y,renderer);
        chart = new JFreeChart(plot);
        chart.setTitle("Gráfico de Energia Renovável do " + jComboBoxCountry.getSelectedItem());
        panel = new ChartPanel(chart);
        panel.setBounds(5,5,430,340);
        
        jPanelGraphic.add(panel);
        jPanelGraphic.repaint();
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jSliderStartYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStartYearStateChanged
        jLabel3.setText(String.valueOf(jSliderStartYear.getValue()));
        jSliderEndYear.setMinimum(jSliderStartYear.getValue());
    }//GEN-LAST:event_jSliderStartYearStateChanged

    private void jSliderEndYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderEndYearStateChanged
        jLabel4.setText(String.valueOf(jSliderEndYear.getValue()));
    }//GEN-LAST:event_jSliderEndYearStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JComboBox<String> jComboBoxCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPaneGraphic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGraphic;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSliderEndYear;
    private javax.swing.JSlider jSliderStartYear;
    // End of variables declaration//GEN-END:variables
}
